language: python
os:
  - linux

python:
  - '2.7'
  - '3.4'

branches:
  only:
  - master
  - development

notifications:
  email:
  - abelcarreras83@gmail.com

install:
  - sudo apt-get install libblas-dev liblapack-dev
  - sudo apt-get install gfortran
  - cd python
  - pip install coverage
  - pip install python-coveralls
  - pip install -r requirements.txt
  - pip install -e .

script:
  - cd unittest
  - coverage run --source=../symgroupy -m unittest discover . "test_*.py"

after_success:
  - coveralls
  - cd ..

deploy:
  - provider: pypi
    distributions: sdist
    user: abelcarreras83
    password:
      secure: "aQudggzWXJPCBBgphxEH9uAu1cIdacqaIq0Zt/N659aIjQjCkYrcP76wQ2JjtgDysAICvPdey04W4x2yrDBRPNHuatRUXpWtFquLYVt4U2FXWdSDWhojZEpuAzDBfO2VCHTs/t8eCaxiEgj4wjGLsCUrTE1HLdpoC3Q5vqtxk50d8B8bwevsjoMPD8yXCEa1CGmNRl0MpfT3c2Z4jOdwrOX/7eVHj5bm4u6F3/6YwCbD6KNfVIRd0ztpQCnmR20uxxt4lBzeRkD4nHANC5+1FKXWR/to2VR4jRhpvwDaAOt1j3OgHzujPcs8QNpnCq5r24MLatcpOR6r64T9YAgOyaCnZqutiA9hXsiSpsIm0c+C+E0b67aEQdS0V75HnDtb12wWtMwv10qt2Q3aCeIP+WRe5F+wfd2u9Lb6jnFUgZXtv/4cl0Rh4E7XeHupRq2/TYCLMSb7PQjjPGWgzIQZrd3RCeElv2NQBj6X52mxRfj08Jhfd2/0l2o8STNJPKaXakuBQQHpAHoYtyi7hrKfifiCRNlBXmlciQmHrCoMAgedY7qFwzq5gFnWDbBn17FSl/DF5QRKr1ftnwWxro91KhRZFmdOzpz7/iQcKFIt7oMXOC9sTmU+k71fyZGuCKTpL3tDHIXpFAyDj6vvfq2y5gy7mSrQHtfH2KhW93AnYAA="
    skip_existing: true
    on:
      branch: master
      tags: false
