language: python

os:
  - linux

python:
  - "2.7"
  - "3.4"

branches:
  only:
    - master
    - development

notifications:
  email:
    - komuisan@gmail.com
    - abelcarreras83@gmail.com

install:
    - sudo apt-get install libblas-dev liblapack-dev
    - sudo apt-get install gfortran
    - cd python
    - pip install coverage
    - pip install python-coveralls
    - pip install -r requirements.txt
    - pip install -e .

script:
    - cd unittest
    - coverage run --source=../symgroupy -m unittest discover . "test_*.py"

after_success:
    - coveralls
    - cd ..

deploy:
    # pypi
    - provider: pypi
      distributions: sdist
      user: abelcarreras83
      password:
         secure: "K/7kzX6KT4ga9lP28VG34D69NfGjgoQOMIfCDu7JEEb4WBhPQnPvdob47DToJ+pEUF82twIPrpv5P0ikkGzSWeGHSzOFZ6aU1zLQGERjknB/4du5APnsFatpRfktamJJG1c8lHkrKj6TMHObLmac65aRNgoYKQ/umP9l61QBiV1E3XfVwOqCDmuOoEvfPIjPHfJF9AuU/36HHeKE3x19jHfVreDkMSNfBUd1kUafTaT2ayyK/UuimYat5iqC8NLoktWNZZ3NdmnLgO0SS6FUEU5mqqsH2d5opFbGvnmIAzyuNrUU5Yw8E4kZK7A140HV41DQV5nad+04MuvBE8zkTdq7F6PAo04TqZ/jofTTDODX7Bz6DH7xb+au01iS+Odkj9ocgTKvBjeZWPS1lcGChPU1MMArTgSD00oP9Aeogz7tKmXR2w1a/p/htwWpCShePs39bTOwkQwQvxZO5RQhJCj/J58AeIYxJAhdhVdmzxT0zmOpAUIDaSM9OCimbahvFj5n16aM5UibDq1gUBJWinuycINw5jbCEWVK6jGpHB9smiXd4VGWICo5yHOuDIYxFinOrpuvi5Qy2lJI4pWJIzA3FTr5gWnR21PUkh3Rcb1WgteAwpIfVz5wM+15u1+0dpBg60yecWO+oPRvEVCD9JjOA/ifMIspylrTFCw+iGY="
      skip_existing: true
      on:
          branch: master
 #         branch: development
          tags: False