language: python
os:
  - linux

python:
  - '2.7'
  - '3.4'

branches:
  only:
  - master
  - development

notifications:
  email:
  - abelcarreras83@gmail.com

install:
  - sudo apt-get install libblas-dev liblapack-dev
  - sudo apt-get install gfortran
  - cd python
  - pip install coverage
  - pip install python-coveralls
  - pip install -r requirements.txt
  - pip install -e .

script:
  - cd unittest
  - coverage run --source=../symgroupy -m unittest discover . "test_*.py"

after_success:
  - coveralls
  - cd ..

deploy:
  - provider: pypi
    distributions: sdist
    user: abelcarreras83
    password:
      secure: "JRZEYCF0veEQAroumrNbpnRQsb7uiRQThg0PgdSZrhdinEJe6kPaDb08ItEBZdwI98V0x/i38AuDPA+lzssP4AKEChF+NmYdri7G8U49WJdN0Txv8NtnY2gKykqSSXp4NjAAYpz21JAPt974UF4X6F5CUb77xMQyqpTEA61ZEI5MrSEcrEhCGQEoLXFKLITmQpPDGvjgGudXuW3O/Ah5Pi/EoL3g/qKkPOGLWI2tzdxKATAVuxzloDeXIYzKBZsjBLGn5yfTAtSoaxJ8jj6BLeDV9R5FKxUCm514F6Dc8rZf1AfVI1tc97FO7/hbB1jmbWEKN0cggxztDxNv343ONad3FB7RfVuNwf/VNZomYsxI1eRpwIMvXRGiEMCmqSK781SmySJD1RzatQL+qfH0gpnEY0T2DYqwiAqVidkXHySopdf7ye2LIx9MWZ+RIeM97mSDxb2RaFJzqizkh49OHbq/PYxTc+am0pdXnPtwWAJrVnEeYu1kT7aLolVTptcEcqI6l3PxHXND8+ZKQTGk3V3K20d6ePytzmHw4spIlaOQzWeMsIbwjPBMvOPxBYZo2UHQp+iMsS+WjwpOkKLgYJI92hxU6cxm1B4JY7IOJ1NXugvsG7/OzaCb/v/CR3AIheyivboekzyObdKILzZPtknjAt7FB7Q4RR/6BopPS7U="
    skip_existing: true
    on:
      branch: master
      tags: false
