language: python

os:
  - linux

python:
  - "2.7"
  - "3.4"

branches:
  only:
    - master
    - development

notifications:
  email:
    - komuisan@gmail.com
    - abelcarreras83@gmail.com

install:
    - sudo apt-get install libblas-dev liblapack-dev
    - sudo apt-get install gfortran
    - cd python
    - pip install coverage
    - pip install python-coveralls
    - pip install -r requirements.txt
    - pip install -e .

script:
    - cd unittest
    - coverage run --source=../symgroupy -m unittest discover . "test_*.py"

after_success:
    - coveralls
    - cd ..

deploy:
    # pypi
    - provider: pypi
      distributions: sdist
      user: abelcarreras83
      password:
         secure: "e69NQZU1dk0YK8DdIhSK6+SrrbHrJFtjAIag5nVuGX6qSeCXpMD4xY7VM22JlPRYbHxYAUcyM55UEM8WNBm+8KUSg9Y4e1iBBzDVNPQmcpmTtoaa31ymQq/HDvtEyrfPBdS17zDzHH2cOIaC/hFgrIc1aadZcqhnvjlBIMzMkxsQO3E6yNosY17TKnTrEM+fzlxzriN6FdWtSfnXlwqIerx7A+w2z2wXW9k9kGdvrlQSkhL/vLS6USZXrHwuHTnbP7tNIGWO0rrlniFZHpZeaeD2KcvSXi4XmfzGWf/4sMlWPc+FKd8H+fJ5kn9QfYuL5A/RNcllEeTYZc+kWYr6Oduq5knqb3xGMAd/c0ZCyzdp4o/rtLZlOD8VFHJoqTN2Ag7EWNoV1YvzhsUwNufj4X2LlVmGFXiZ4YXZzxegJR0bv8huK+qfr5PMXkWtdWwJN8OzGrB6NvhZxh54LR0Ca/sRSaaOTlnAm0XO65Ub2US+LdBvZCu+gAz59BEieDooSuyEoK7N7pmUcCrBm7iIs8j8PA1zf5ZoYW3QdcHXn/xmH0xRqw+wgR+uC60X+ksquzC5RaPT82BoMkW3DtxqiSFd59qIU67Tysik+Yr0+xHQVhQT8tYljBQRa2qkfGfgIYFnJ1NXKnAH1wH9Tb1Vj4shxH/RcT4U7Er2mCfw9R8="
      skip_existing: true
      on:
          branch: master
 #         branch: development
          tags: False