language: python

os:
  - linux

python:
  - "2.7"
  - "3.4"

branches:
  only:
    - master
    - development

notifications:
  email:
#    - komuisan@gmail.com
    - abelcarreras83@gmail.com

install:
    - sudo apt-get install libblas-dev liblapack-dev
    - sudo apt-get install gfortran
    - cd python
    - pip install coverage
    - pip install python-coveralls
    - pip install -r requirements.txt
    - pip install -e .

script:
    - cd unittest
    - coverage run --source=../symgroupy -m unittest discover . "test_*.py"

after_success:
    - coveralls
    - cd ..

deploy:
    # pypi
    - provider: pypi
      distributions: sdist
      user: abelcarreras83
      password:
         secure: "ZhfKqglYeazKQJMPzRjj0adMzNKiRPt8mBjg/G9bBZ/XuaLBRkazv/YbNfW4rirEjNr/yk2juVXytF58TajutmfeKRaUpH+0GLQ5gMCi+7xbkNBz5isrMz1+xVDN+JLVAreGjyUhZIP+/5+g7PNCXwnekdC/e9pE4JoLmuL5AE8qtHGjcR/PVc1+6wEy4x+fherblBRAcswrSDbPChFefDmeQoDcBKsvxMgrsplTcFDC5nAoANtAPW94KMYy5Fs9bZpGts3e2cqLucE/bsUtwMQe7qS76sIXKIWRUFXQ3MjNGyNwUlR8BxFYpw6ZpSK4iNN7SVydnkHwCHSLNA85bpHJ2a1VWbt5y5ywDM4XXdmxwQEwIAtYNzuTN/miCgrBZqAWdJbX2/6GZsF0KIvfyhqhDRNZb/EmJTYWI3cxDf7OjbiEpKg41Ajh/ZR7nmaDt6VwkpdbfJOAOK02O/9Qe1xdNIO9OqOP/C3BBNuEdkHVOOS9FlWUXARW/Y2se8qSSFhmYlaoqCleJ3HnwQFZyE4D83hGQy8Jz3Y7Llx7sHcufdG1iAImSzxNUwK/6UElfP6mG5ffCMGcqz3Gtao7SBZdR+8AeOYcjL9sLQKQFvk7F0MBHTEUtlYeGqbQ3px+efGCFV8GwNimm0Zc+c6kviH97XOeJU23iU/oOQhgano="
      skip_existing: true
      on:
          branch: master
 #         branch: development
          tags: False