language: python
os:
  - linux

python:
  - '2.7'
  - '3.4'

branches:
  only:
  - master
  - development

notifications:
  email:
  - abelcarreras83@gmail.com
#  - komuisan@gmail.com

install:
  - sudo apt-get install libblas-dev liblapack-dev
  - sudo apt-get install gfortran
  - cd python
  - pip install coverage
  - pip install python-coveralls
  - pip install -r requirements.txt
  - pip install -e .

script:
  - cd unittest
  - coverage run --source=../symgroupy -m unittest discover . "test_*.py"

after_success:
  - coveralls
  - cd ..

deploy:
  - provider: pypi
    distributions: sdist
    user: abelcarreras83
    password:
      secure: "TAsK7yVKMLWddoGUpWDiiM9FNonk970/eeHnZp5+PqdsLDFRdlHPOU9VcJZmQ4wdkXDkXqu/iGZJUfZ/kS3Um5iamooKk0Isva2RwCEAecRCO1UGp5pSruPgZjsVuQnV0VrgJG9WdQnh5Ro5XVFECgRh0EDJZ0WXRul+4y07K963nTtWVPds6qRhE1vyV+0L1kZzlOTa/npcQLJBeJa21oacNlnk+a+7Z0aQaTmYaCjJ4Si/l7a9GKtDNjS+5RojNOILyPHD8b+bLe1ZXa3H9zCaHSHv3SQReMO/vTmqzAVNMQW5HHpe8T1dqXxLdXSpUmEez2q3rbnHsRDPVawJqx/i0guiyC5M3tEkoISKa0aHrx5JJYohKw/31+ZxAkyjBgIlDCUI3UBVQAi6R/xxolJ5mB3SMj24EZBMbJg4KfOkI8tjKbYKu7ih01AmkvDe43C5mjh7FWUDHVtEbXn3MIJ8Yd78HNiqaJuzUaQ1xzj7/TD2SeZWbpwMq9CbOh6YG/IDDLvz0RJdEGWT4PMsycV/m/2vQogdtpEP8kWI8o/If/UVBdGUfpaPhvPQDW910M5QXncmcATpwxGQD6LsH/0DiMjJCRdlgs4RgyNTTZYVi2S3ccwE1ImzaK733Mcmk42fxZu9CgYtjlhYRIBgr28D7rf7ZspSyVLioPuCNYk="
    skip_existing: true
    on:
      branch: master
      tags: false
