language: python
os:
  - linux

python:
  - '2.7'
  - '3.4'

branches:
  only:
  - master
  - development

notifications:
  email:
  - abelcarreras83@gmail.com

install:
  - sudo apt-get install libblas-dev liblapack-dev
  - sudo apt-get install gfortran
  - cd python
  - pip install coverage
  - pip install python-coveralls
  - pip install -r requirements.txt
  - pip install -e .

script:
  - cd unittest
  - coverage run --source=../symgroupy -m unittest discover . "test_*.py"

after_success:
  - coveralls
  - cd ..

deploy:
  - provider: pypi
    distributions: sdist
    user: abelcarreras83
    password:
      secure: "g/G7Ev7lV/Lb2GKNJLmgy2ZR95Yt8vcm0AlZs1S+uXoDxdwNC8Dxa1bMZufLXg1OCPhu42I+n+0Xbl7Y6knvkQU3p90Mr3JTTQI/MWDiOP3maPF3nqCq9XrZz6RckA7bzyvG8aO0iCFoe/D3rX94FZs2zIX3YQ90WEc6S2b2LVmSmU+fpEl8I5lWhDhwKtGmHtnVhaIUmdXuSLqJdc4K84g/GfBsXWbZHBEfCYJ7F3p0S69qf/Xk8BGwvXWHJ7gXhx7k37m954iFH8RKlrNDUky7khuAm8u7uqpEQxIu+3b+idcfk7yliKFUYN6AOlv0OG2fSMWTI0p5o8cOunFeqHcy3raAU8ArQWn4ZQLGA8AwsdASSetUZPlD6swKzVwLMxtMuIW4veu292PUxD/yV6g3jV/w41i9UCQMG67QWt1FaF3/L+e/iPwvn+So82FTwwppUlZszSwRFh/T9kcAnyz7JI3FQ9kr1CAq9tW46pHKUMI+VfKe/+R/CQze0WTG/m6Eqc6IXHdo/aAES8ihoUTdLQp7nj4mGQ0aIU/OH8t6GYveno9tDrIQjc3bm73SJcRrQrrZtT+cZ0I8JpbpzmLnmxho7gyCibtGP++KwtPwVhEGaP4kquipgo6LcGhocSfO8eVvUkmtTEGYr+MzvwKXmaLO5+b1BBZG9OHzX6w="
    skip_existing: true
    on:
      branch: master
      tags: false
