language: python
os:
  - linux

python:
  - '2.7'
  - '3.4'

branches:
  only:
  - master
  - development

notifications:
  email:
  - abelcarreras83@gmail.com

install:
  - sudo apt-get install libblas-dev liblapack-dev
  - sudo apt-get install gfortran
  - cd python
  - pip install coverage
  - pip install python-coveralls
  - pip install -r requirements.txt
  - pip install -e .

script:
  - cd unittest
  - coverage run --source=../symgroupy -m unittest discover . "test_*.py"

after_success:
  - coveralls
  - cd ..

deploy:
  - provider: pypi
    distributions: sdist
    user: abelcarreras83
    password:
      secure: "AQQaSsAQNrnAMAOXjGwBsHg/5ApWU2Q1ZsCOac5yJQ5JxH0m/dttLnc1E5l9nQ1IgDEVGDxUv0QQ7GK2G5UQQtmDCdC9dFvWdYueRuX0lz3X9RfNzuV6uBmgUr6sqkBGOgKFF4kOeU4w0JKqnZ4K2oBrJWm4uhjCA/2bppQjV9Yv5dWfKLfxaBKX8afpM/PenYCNhxmqOTUrn/HwYJal902/+fLWqXNmkddCSvWqX/k3cp2in08OiTYgW8edU53bvGJFG6Yrqd6Lv3K5VPeSTS00W4BW6VtTrLrb/OFMRQ3ZAJ/fo93CDGIrWfUFIh2D4Qi3gp7ksO1jLV9uHNz1RJaKIq3m9/zGKPuDCGjOLyAcBOkMYfYgNp+MDRpzFZX158Qj/gQLVb6rHLJFfAmSNDRYGB8TNy9izHz70A5yfI9+L2ATn1LM6Z11Dx9jdMfjJtkINBpLsA+9psH8ACThf922C4GoJKHMaytNVRpMAq0IQLcaIV7pNvKLrZCzDEZalxefWpkF2aUVrJ2PcOudoevXsJ8EcBrgjlD9dehU4GbAndONaaLyLBnbpYApQXeyBaNTbhGxqhZQ7glnwcSI+cr77osFRPGClBpZ6ledN6XEIi6MudJVRXmG+GZBgpowAqJ0TPyyFSEfcZs8IqGM0UbwfeDipTeU/hykWJJgMNI="
    skip_existing: true
    on:
      branch: master
      tags: false
