language: python

os:
  - linux

python:
  - "2.7"
  - "3.4"

branches:
  only:
    - master
    - development

notifications:
  email:
    - komuisan@gmail.com
    - abelcarreras83@gmail.com

install:
    - sudo apt-get install libblas-dev liblapack-dev
    - sudo apt-get install gfortran
    - cd python
    - pip install coverage
    - pip install python-coveralls
    - pip install -r requirements.txt
    - pip install -e .

script:
    - cd unittest
    - coverage run --source=../symgroupy -m unittest discover . "test_*.py"

after_success:
    - coveralls
    - cd ..

deploy:
    # pypi
    - provider: pypi
      distributions: sdist
      user: abelcarreras83
      password:
         secure: "i884aX9kbApW8VcIjrkyaeaxfMKvym+zSxkLu6K4ae5/BM1SXiouNToAGZGcv3DzDHb/MLLg+YuDMLEM9Vo2d5M7W4e0VNU72NYcASH3POx9B6xGVv/gSCZ6b3oYpmOAF5PCs7IgYaqZ+L4Mz55WBmWSH/Y9vXtdsZ/oi5zRpeBHDM1f52GgnfAsX+xim16oPwSVVIHx3Wn+bH+MdMSfJGEO/ut04aXk0R4QsaGYGTQrqQl3HJ1Z8x9V+/OCmOnTvyt2iK1BESR73bhUg7jhti8jcCgM7ReJ6bR8Q2QxolHYsOgpoLGyk3oq6UFkSEfM8vHcbIpnM1PYNwgPENlP5UvK3BcmBXJKr/fzkud+basXc4QGHednrLkzI4o7YcAgK9GWqixsRC9/ifWpmovIs1VxI6j1ogg6Bb+jjOfjpwi6cqpCQ5glLFR+YjRq3iVsbi7O21l7HWOdu6h2YIAG5d4AJ6oDOdN7DQ47jyzk47n+rnxfPhH504s8Cm12yt54yU+12We03tnIa+19kbyHzy2bLXASrzWwvTPD8WJyfnIHPmLxdv2yhYD62wmITHjTmKiqoStgfmiRfadxsRdCxY+XNBty+0+hXYqATtynDM9UPsVhk6G9zXeOaR70ub3CiPVKXV/ZPSVw9NHd3gefOTnTsjuVTM5/xdLn+7KWOlI="
      skip_existing: true
      on:
          branch: master
 #         branch: development
          tags: False