language: python

os:
  - linux

python:
  - "2.7"
  - "3.4"

branches:
  only:
    - master
    - development

notifications:
  email:
    - komuisan@gmail.com
    - abelcarreras83@gmail.com

install:
    - sudo apt-get install libblas-dev liblapack-dev
    - sudo apt-get install gfortran
    - cd python
    - pip install coverage
    - pip install python-coveralls
    - pip install -r requirements.txt
    - pip install -e .

script:
    - cd unittest
    - coverage run --source=../symgroupy -m unittest discover . "test_*.py"

after_success:
    - coveralls
    - cd ..

deploy:
    # pypi
    - provider: pypi
      distributions: sdist
      user: abelcarreras83
      password:
         secure: "JSGM1eUOpIiuYpQbRr3evJtF73pSqluFFfnGICkifLW5wz70Gxr7hfHw2X8LJndWY/xDNxrcVqSalSiM8sJjtU4hHTZ89HyUPY8jaOfUfGg3gZsegPcup0mbXlwKxvpfpmNBwOizcaaG1c0Nzyc/hlctT+nyKJRgQWGkVye3er/U+cKo/CpAsIEGZSM7JROsMMSmszKDiR8bl38Q79qd/pBIvHzbKsBE6tIxhXOcs5vO1tRvgG9maLIGCy53VhTtJ2GLsiJwjQLGewItXbiHXx/tEYsAqccYhRsbsnnY7sokeNoI5H/w3I9Ls2+HMYprlMVWj9GzuOtBdhc+WjGhb5VInmh3KUwsf97tk6SFWAulfJHHxfP/C1ozEntbZdn6bREiOWyf3qqHoC6yNk9/FD7RncqIuvabiy0mS5BaSqnoKTTGjnK2rUy71CBT4RUvPDq7aFhgHGEea8lbvcnOXqJI5ns+9eT0VoFTuC+OegVF9xnftabO3xw3ZRSSEHsN51MFAJGhFta5JUisSAyIAVMuGAFZ5d7VU7zzOnLS2qMjbz0NAYwBSISyP+PphyQxYJLGxxEJzozp8uv32MJaguLOElVvkbzE3NmCLpdYiR5xhC9OfoPknZUpmBLJEezwxkSfVzghsaw9weeq+SYSkFxqbJaBHdBVJwiELqgRdpI="
      skip_existing: true
      on:
          branch: master
 #         branch: development
          tags: False