language: python
os:
  - linux

python:
  - '2.7'
  - '3.4'

branches:
  only:
  - master
  - development

notifications:
  email:
  - abelcarreras83@gmail.com

install:
  - sudo apt-get install libblas-dev liblapack-dev
  - sudo apt-get install gfortran
  - cd python
  - pip install coverage
  - pip install python-coveralls
  - pip install -r requirements.txt
  - pip install -e .

script:
  - cd unittest
  - coverage run --source=../symgroupy -m unittest discover . "test_*.py"

after_success:
  - coveralls
  - cd ..

deploy:
  - provider: pypi
    distributions: sdist
    user: abelcarreras83
    password:
      secure: "CYKHdk+Y1rnp2uIBjG2r5qKOd95w6b3hmnTI1qvZMmZSNe3snx+8RW03gp/BbnRmvv1mZ4UHRvutazvWS0EFqawDveo11XHj6OYTsm38D85NEDbT+Z7mHuuhbDDbIA0KEKON5dCxEZg/9P5o8z16nZVPbi9mWsukbLBgXb+ijwnxuCl6pCSAfpya+pIxzgiWanhI9Nc6tNnABxARqeryorKW1X76tHlbqg9/EzcOiDtfjW3PEcaIqF0USnLY17mx1quCGUkwRxDx7lUlt7JoDg8Pf4AbImBWsMxHovqHvTMNkDVvAk9OY6Y1Dy94rTCbQrjFbjit2e5Dim+HlWohsU5AQufLvsCnBqU0llCPElhOEsog3HEl27uOM0bFBCK8TZW/e2SBPe32pjC+bZqkSvxJegEWizLZVazimq2v/+Tsl2+YiQneA9oiffghgW+c+yWpPl+ZLuYR0X/BjifVzUVesa3adbM2Exr5k2QXOi3H1Pf9subwyKuQ42naDE8iLJaUGY+ywo+wXHoH15RriKZh1EgVgVUdzuT+rys6FBkJ1vyLbcBLMzMl9nO/q0qUGnQdzX+TSR4jSHASaYNZsJJBPhueWzTifoH2Y9QaIl40k4mDXoix8ivNor0nW/R5hrzvHsHqnL+mSMbQDpSR3HNpy879CBoHtVz/IEnpmMY="
    skip_existing: true
    on:
      branch: master
      tags: false
