language: python
os:
  - linux

python:
  - '2.7'
  - '3.4'

branches:
  only:
  - master
  - development

notifications:
  email:
  - abelcarreras83@gmail.com
#  - komuisan@gmail.com

install:
  - sudo apt-get install libblas-dev liblapack-dev
  - sudo apt-get install gfortran
  - cd python
  - pip install coverage
  - pip install python-coveralls
  - pip install -r requirements.txt
  - pip install -e .

script:
  - cd unittest
  - coverage run --source=../symgroupy -m unittest discover . "test_*.py"

after_success:
  - coveralls
  - cd ..

deploy:
  - provider: pypi
    distributions: sdist
    user: abelcarreras83
    password:
      secure: "WB5FMA7WIoW0FRHCtkuPNq9XkdpcJ7EskLwQIqEnyK9hZ3JRdrEVsqwQdRq1VzRPgjoZi9RjbU0UYBsM9wkmEE5CXnDJScnWizSmbFs+vqn+0kMNlPvhWqgjKFM21EnSo8YQvkGT0yvWYMyAwiBQ/gl4BaR4suwxWSqj2+SHpy3SmyibG8M6TKM/LG8b+Q7opC/W0LPjO0yvIIhUO7qIXnMZccMtSGCsqTCeodQMe4C0oQCA5ext12jphGLACwSr8RWemmGijsnvZJh0QqbgVsOgwPIw76WcsOfyyFKFOK0UIoOc6HIFGlLIpVM3YM4uc2M0DtaBM456E5suc7csVR3mruNjBnEyHolj2p29ZQYjvxfNqhgMy1bCWiqBWmLuBJ1sE57TamStBDmhzs+79z9c8oOzWXfN/65gOAGrcNfyYjFCy/kqpU6HOFE46lOz5bksQ2gh3Rcdw7NR6faJSw2frREu35JfTjOzkuxXNBXGxxxL5rlkxT1lBvVRDz/r6tJ+5BomyFOvcKERHAfbQbt0HQvt2xcAkwgypzoQNE1Zj+b2kV8AwV99Zc0R4VOF8VBofOlB0qKZRkk6CP9+GaZ5+tUN0fTet9LfMwzLt7dkBDC97AR7U1TK7VSgaJDDtE6g5FcscHiaHcKFQKSztVck+uO+UXglQmc7zPnnYbw="
    skip_existing: true
    on:
      branch: master
      tags: false
