language: python
os:
  - linux

python:
  - '2.7'
  - '3.4'

branches:
  only:
  - master
  - development

notifications:
  email:
  - abelcarreras83@gmail.com
#  - komuisan@gmail.com

install:
  - sudo apt-get install libblas-dev liblapack-dev
  - sudo apt-get install gfortran
  - cd python
  - pip install coverage
  - pip install python-coveralls
  - pip install -r requirements.txt
  - pip install -e .

script:
  - cd unittest
  - coverage run --source=../symgroupy -m unittest discover . "test_*.py"

after_success:
  - coveralls
  - cd ..

deploy:
  - provider: pypi
    distributions: sdist
    user: abelcarreras83
    password:
      secure: "THQAbRZ/mGqTRmzQkTU2ouFH/jsy+5NNAr0EmuWv7bIPWtJNgOy9VG6FIa4ANmHc88XgGEC9D3WpGB8VVXZFywJOrsGDBOOI4ya4Mzu6K/ivs3IUU6a1xcIlnvurVeb+W1+18ZbcsRbYOklpuxodDLKljxbdiezedTlJJuw2dD4b3rSF2HyGipbs98jARpQhCMVNLhChs6+8zSdIMrWW7zrc7YBINg8KmTtZljvx2X8WxGn2i/Ng2Foz8fBGHhnOnu/G0Ef24RjOqWQw3gN6qfcL539KG7P45zHMFF1NLbAmOgqqEUF1YLABKh5k0XLqPFcuFZjiXPkhw7ZeTciAJ3rnsoL9buLYiDTCdhouEnOV414d+FssPvk/WeEYhXD3gDwf7zGWbEhohHjmq8XUnMcx3KnNi3uivO9XJMhOP/yt8XHfvZgcayV0meoM4ZsguB4UC5EPdIrbQYvkOVn2vKNZMmPg09nvNsQDiXEueckC0OhlvHpnQqkh+yaWGqJZwHg0kKYF0jNm9lrGb6lvBox8R+x4FcjFWLvU08oln+grMzkf7M+bN0FYIjeq0L0/tUmIedq+970wGehs1aJvgRyMwoHbXy3v4/Zu+BGldJVBlVOewoFzwTIYm+1hv3xwvLruBr9/yRsRKlKfKdvvjb7+Rp6iwbNKQqDvLD87IA8="
    skip_existing: true
    on:
      branch: master
      tags: false
